In [2]:
import numpy as np
from aocd import get_data, submit

DAY = 2
YEAR = 2024

In [3]:
# use test data
raw_test = """7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9
"""

# use real data
raw = get_data(day=DAY, year=YEAR)

print(raw_test)

7 6 4 2 1
1 2 7 8 9
9 7 6 2 1
1 3 2 4 5
8 6 4 4 1
1 3 6 7 9



In [14]:
raw

'40 42 45 46 49 47\n65 66 68 71 72 72\n44 46 49 52 55 59\n62 63 66 68 71 74 80\n20 23 25 24 26\n37 38 35 38 39 38\n82 83 80 82 83 83\n69 72 75 74 77 79 83\n23 26 24 27 34\n59 62 62 65 67\n21 24 24 27 30 32 29\n56 57 58 59 59 62 62\n72 75 77 77 81\n79 81 81 83 86 93\n6 8 11 12 16 17\n13 16 20 23 24 21\n85 86 88 92 92\n74 76 78 82 85 88 92\n3 5 6 8 12 18\n48 51 54 61 63\n48 51 56 58 61 63 65 64\n13 14 19 20 23 23\n25 27 34 35 36 40\n59 61 64 67 68 73 74 81\n61 60 62 64 66 67 68\n19 17 18 21 20\n94 92 95 97 98 98\n75 72 74 75 78 82\n49 48 50 51 56\n42 39 40 41 40 41 44\n42 40 42 41 42 40\n70 67 64 66 66\n50 48 49 48 51 55\n66 65 68 66 67 69 75\n91 88 88 89 90 91 92\n28 25 27 29 29 31 32 31\n77 74 75 75 75\n86 83 85 85 88 92\n26 23 24 24 27 33\n48 45 47 51 54 56 58\n43 41 42 43 46 50 49\n20 19 22 25 26 30 30\n11 10 14 15 19\n19 17 20 23 26 30 37\n23 20 21 24 26 31 34 36\n94 91 96 99 97\n88 86 88 89 92 98 98\n19 16 18 21 27 29 32 36\n69 66 67 69 75 80\n2 2 3 6 7 8 9 10\n69 69 70 72 74 75 76

In [ ]:
def parse_data(data):
    data = [np.array(d.split(' '), dtype=int) for d in data.split('\n') if d != ""]
    return data


dummy = parse_data(raw_test)
real = parse_data(raw)

dummy

[array([7, 6, 4, 2, 1]),
 array([1, 2, 7, 8, 9]),
 array([9, 7, 6, 2, 1]),
 array([1, 3, 2, 4, 5]),
 array([8, 6, 4, 4, 1]),
 array([1, 3, 6, 7, 9])]

# Part 1

In [34]:
def is_safe(row: list[int] | np.ndarray) -> bool:
    row = np.array(row)
    is_monotonic = ((np.diff(row) > 0).all() or (np.diff(row) < 0).all())
    safe_diff = abs(np.diff(row)).max() >= 1 and abs(np.diff(row)).max() <= 3
    return (is_monotonic and safe_diff).item()

data = real
result = np.count_nonzero([is_safe(row) for row in data])
result

680

In [26]:
submit(result, part="a", day=DAY, year=YEAR)

That's the right answer!  You are one gold star closer to finding the Chief Historian. [Continue to Part Two]


# Part 2

In [35]:
def is_safe_dampened(row):
    if is_safe(row):
        return True

    for idx in range(len(row)):
        temp = list(row.copy())
        temp.pop(idx)
        if is_safe(temp):
            return True

    return False

data = real
result = np.count_nonzero([is_safe_dampened(row) for row in data])
result

710

In [33]:
submit(result, part="b", day=DAY, year=YEAR)

That's the right answer!  You are one gold star closer to finding the Chief Historian.You have completed Day 2! You can [Shareon
  Bluesky
Twitter
Mastodon] this victory or [Return to Your Advent Calendar].
